### ISSUE TITLE
Unable to sync; wrong datatype for Cipher.Attachments

### ISSUE THREAD

**Issue by Omar007** [mvdan/bitw#10]
bitw sync fails for a database with attachments.

Currently, Cipher.Attachments is defined as a string array but this does not match with the actual format returned by Bitwarden.

The actual datatype returned is an array of Attachment objects. The object has the following properties:
```
FileName:string
Id:string
Key:string
Object:string
Size:string
SizeName:string
Url:string
```

**Comment by mvdan** [comment]
Thanks for the report! I can have a look later this week, but feel free to beat me to it.
