### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by il-mich** [mvdan/bitw#26]
Hello,
I'm trying to use bitw but I'm unsure where to start. I'm not familiar with Go and `go get`.

Typing
```
cd $(mktemp -d); go mod init tmp; go get mvdan.cc/bitw
```
doesn't seem to install the program, or even build it as far as I can tell.

It just creates a folder in `/tmp` with the files `go.mod` and `go sum` in it.

I'm probably missing something but I'm not sure what. Could you please explain to me how to install this tool? Thanks!

**Comment by mvdan** [comment]
I get that the line is confusing, it will be easier with Go 1.16 when it releases.

The binary will be in `~/go/bin` by default.

**Comment by il-mich** [comment]
Damn! How did I miss it?

Thank you very much for your help!
