### ISSUE TITLE
Outdated install instructions

### ISSUE THREAD

**Issue by desttinghim** [mvdan/bitw#36]
I am getting the following error when I attempt to login. I've installed bitw using the instructions in the readme.
```
error: could not login via password: Bad Request: {"error":"invalid_grant","error_description":"Auth-Email header invalid."}
```
This would be easier to debug if bitw could print out it's version. Can the install instructions/package be updated?

**Comment by mvdan** [comment]
It sounds like the install instructions worked just fine; otherwise how were you running bitw at all?

The error you got sounds like https://github.com/mvdan/bitw/issues/31, which I thought we had fixed.

**Comment by desttinghim** [comment]
It is #31. When I used `go install ***@***.***`, it was pulling an outdated version of the library, which I figured out by looking in the go directory. After I realised this was the case, I just cloned the repository and built it. That resolved the problem for me, but it was quite frustrating until I figured it out.

**Comment by mvdan** [comment]
Oh my - you're right that `go install mvdan.cc/bitw@latest` installs a version that is massively out of date. That is entirely my fault - I broke the `https://mvdan.cc/bitw` pointer to GitHub some time back and never realized. Apologies for the confusion - fixing it now.
