### ISSUE TITLE
Support all 2FA types

### ISSUE THREAD

**Issue by HarHarLinks** [mvdan/bitw#38]
I've set up a Yubikey 5 NFC with both FIDO2 and Yubikey OTP 2FA methods. I can't log in due to
```
$ bitw sync
Password: 
error: invalid two-factor auth provider: "7"
```
Related: #15

Thanks for your work on this!

**Comment by mvdan** [comment]
Indeed, these are TODOs. I only implemented the one that is easy to test locally, which is also what I use.
