### ISSUE TITLE
Auto-fill

### ISSUE THREAD

**Issue by leath-dub** [mvdan/bitw#47]
I understand this is out of scope of this project but I can't find anywhere online on how to setup autofill for libsecret dbus service. This project is working great but is `secret-tool` the only way to access secrets ?

**Comment by michaelk83** [comment]
Client apps that support the Secret Service API (`org.freedesktop.secrets`) can save and access their passwords via libsecret (on KDE this is typically through QtKeyChain, which can access either libsecret or KWallet under the hood). I'm not aware of any libsecret clients that can perform Auto-fill/Auto-Type, and there is generally a problem implementing that under Wayland.

**Comment by leath-dub** [comment]
> Client apps that support the Secret Service API (`org.freedesktop.secrets`) can save and access their passwords via libsecret (on KDE this is typically through QtKeyChain, which can access either libsecret or KWallet under the hood). I'm not aware of any libsecret clients that can perform Auto-fill/Auto-Type, and there is generally a problem implementing that under Wayland.

That makes sense it was actually just that issue #46 was why it wasn't working. I think it's something to do with no organization id

**Comment by mvdan** [comment]
Other tools like https://github.com/quexten/goldwarden do have a GUI and desktop integration with autofill/autotype. This tool instead takes the route of D-Bus, which I understand to be different and also a bit lower level. My initial impression is that it wouldn't make sense for either tool to try to support both, but I don't hold that strongly.

I'll clarify this in the README.

**Comment by leath-dub** [comment]
> Other tools like https://github.com/quexten/goldwarden do have a GUI and desktop integration with autofill/autotype. This tool instead takes the route of D-Bus, which I understand to be different and also a bit lower level. My initial impression is that it wouldn't make sense for either tool to try to support both, but I don't hold that strongly.
> 
> I'll clarify this in the README.

Thanks, that clears things up
